tsukuyomi.user.list1 = tsukuyomi._consume_data(0)
local __Var2 = tsukuyomi.core.car(tsukuyomi.user.list1)
tsukuyomi.core.print(__Var2)
local __Var3 = tsukuyomi.core.cdr(tsukuyomi.user.list1)
tsukuyomi.core.print(__Var3)
local __Var4 = tsukuyomi.core.cadr(tsukuyomi.user.list1)
tsukuyomi.core.print(__Var4)
local __Var5 = tsukuyomi.core.first(tsukuyomi.user.list1)
tsukuyomi.core.print(__Var5)
local __Var6 = tsukuyomi.core.rest(tsukuyomi.user.list1)
tsukuyomi.core.print(__Var6)
local __Var8 = tsukuyomi.core.rest(tsukuyomi.user.list1)
local __Var7 = tsukuyomi.core.first(__Var8)
tsukuyomi.core.print(__Var7)